[theme] # You have to add this line

primaryColor = '#31473A' # yellow hover and select

backgroundColor = '#EDF4F2' # purple background

secondaryBackgroundColor = '#6AB187' # Pink element background

textColor="#31473A"